version: "3.9"

services:
  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=github_repos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 20


  web:
    build: .
    command:
      ["./start.sh",]
    volumes:
      - .:/github_repos
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  static_volume:
  files_volume: