# Generated by Django 4.2.8 on 2023-12-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=50)),
                ('repo_name', models.CharField(max_length=120)),
                ('html_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'GitHub Repositories',
            },
        ),
    ]
